---
# from galaxy
- src: geerlingguy.glusterfs
#- src: nickjj.docker
#- src: andrewrothstein.gitlab-ci-multi-runner
#- src: DavidWittman.redis
- src: andrewrothstein.virtualbox
- src: haxorof.docker_ce
- src: mrlesmithjr.mdadm
  version: v0.1.2
