---
# Default variables for all ephemeral nodes
# rename to all.yml

sysctl_list:
  - name: "vm.dirty_writeback_centisecs"
    value: 6000
    state: present
  - name: "vm.dirty_ratio"
    value: 80
    state: present
  - name: "vm.dirty_background_ratio"
    value: 50
    state: present
  - name: "vm.swappiness"
    value: 1
    state: present
  - name: "vm.vfs_cache_pressure"
    value: 100
    state: present
  - name: "vm.page-cluster"
    value: 0
    state: present
  - name: "net.ipv6.conf.all.disable_ipv6"
    value: 1
    state: present
  - name: "net.ipv6.conf.default.disable_ipv6"
    value: 1
    state: present
  - name: "net.ipv6.conf.lo.disable_ipv6"
    value: 1
    state: present

package_list:
  - bc
  - bison
  - build-essential
  - chrony
  - flex
  - git
  - libelf-dev
  - libssl-dev
  - lm-sensors
  - lz4
  - mc
  - network-manager
  - python3-pip
  - sshfs
  - sysstat
  - vim-nox
  - virtualenv
  - virtualenvwrapper
  - xz-utils
  - zstd

# Glusterfs setup for pasture_glusterfs
glusterfs_vol_name: pasture
glusterfs_mount_dir: /mnt/pasture
glusterfs_server: k0.local

ansible_ssh_user: vagrant
ansible_python_interpreter: /usr/bin/python3
ansible_sudo_pass: "vagrant"

tmpfs_mount_dir: /tmp
tmpfs_size: 1G

docker_compose_url: https://github.com/docker/compose/releases/download/v2.29.3/docker-compose-linux-x86_64
docker_compose_sha256: 241b75fe0f8194a48d01f99d683aa1100579b21caa60d2d78c9c824855c57937
