---
# This only creates the gluster volume with all the bricks
- name: Setup brick dir if it is not a mounted dir
  file:
    path: "{{ glusterfs_brick_dir }}"
    state: directory
    mode: 0755

# reference:
# https://github.com/kubernetes-sigs/kubespray/blob/master/contrib/network-storage/glusterfs/roles/glusterfs/server/tasks/main.yml

- name: Create glusterfs volume with replicas
  gluster.gluster.gluster_volume:
    state: present
    name: "{{ glusterfs_vol_name }}"
    bricks: "{{ glusterfs_brick_dir }}"
    cluster: "{{ ansible_play_hosts }}"
    replicas: "{{ glusterfs_replicas }}"
    rebalance: "{{ glusterfs_rebalance }}"
    force: true
  run_once: true
  when: glusterfs_replicas | int > 1

- name: Create glusterfs volume without replicas
  gluster.gluster.gluster_volume:
    state: present
    name: "{{ glusterfs_vol_name }}"
    bricks: "{{ glusterfs_brick_dir }}"
    cluster: "{{ ansible_play_hosts }}"
    force: true
  run_once: true
  when: glusterfs_replicas | int <= 1
