---
# Specific vars for host swarm0.local
# these are for mdadm role
mdadm_arrays:
  # Define array name
- name: 'md0'
  # Define disk devices to assign to array
  devices:
    - '/dev/sda'
    - '/dev/sdb'
  # Define filesystem to partition array with
  filesystem: 'ext4'
  # Define the array raid level
  # 0|1|4|5|6|10
  level: '0'
  # Define mountpoint for array device
  mountpoint: '/mnt/md0'
  # Define if array should be present or absent
  state: 'present'
  # Set mount options (optional)
  opts: 'noatime,discard'

#############################################################
# These are for
# * geerlingguy.glusterfs role (server)
# * geerlingguy.glusterfs role (client)
# These override the vars set in inventory/group_vars/all.yml
# They are specific to each host and the last
glusterfs_mount_dir: /mnt/gstore
glusterfs_brick_dir: /mnt/md0/brick0
glusterfs_server: swarm0.local
glusterfs_vol_name: gstore

