---
- name: Setup mount points
  file:
    path: "{{ tmpfs_mount_dir }}"
    state: directory
    mode: 0755

# remount will block writing to /tmp atm
- name: Mount tmpfs
  ansible.posix.mount:
    fstype: tmpfs
    opts: "size={{ tmpfs_size }},noatime,defaults"
    path: "{{ tmpfs_mount_dir }}"
    src: tmpfs
    state: present
