---
# Setup .vimrc for root
- name: Upload .vimrc for root user
  copy:
    src: files/vimrc
    dest: /root/.vimrc
    owner: root
    group: root
    mode: '0644'

# Setup .gitconfig for root
- name: Upload .gitconfig for root user
  copy:
    src: files/gitconfig
    dest: /root/.gitconfig
    owner: root
    group: root
    mode: '0644'
