---
# Specific settings for nodes that send telegraf metrics
influxdb_hostname: metrics
# set this per host or at runtime
# influxdb_token:
telegraf_agent_version: 1.32.3

telegraf_agent_package_method: online
telegraf_agent_hostname: "{{ ansible_nodename }}"

telegraf_agent_output:
  - type: influxdb_v2
    config:
      - urls = ["http://{{ influxdb_hostname }}:8086"]
      - token = "{{ influxdb_token }}"
      - bucket = "metrics"
      - organization = "neofob"
      - timeout = "5s"
telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = false
      - totalcpu = true
      - fielddrop = ["time_*"]
  - plugin: disk
    config:
      - ignore_fs = ["devtmpfs"]
  - plugin: diskio
    config:
      - devices = ["sd*", "nvme*", "tmpfs"]
  - plugin: mem
  - plugin: net
    config:
      - interfaces = ["eth*", "eno*"]
  - plugin: swap
  - plugin: kernel
  - plugin: sensors
  - plugin: system
  - plugin: docker
    config:
      - endpoint = "unix:///var/run/docker.sock"
      - perdevice = false
      - perdevice_include = ["cpu", "blkio", "network"]
      - total = true
      - total_include = ["cpu", "blkio", "network"]
